/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCasesRouteImport } from './routes/app.cases'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppRecordRouteImport } from './routes/app.record'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppVeritasRouteImport } from './routes/app.veritas'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as RegisterProfessionalRouteImport } from './routes/register.professional'
import { Route as RegisterProfileRouteImport } from './routes/register.profile'
import { Route as RegisterSuccessRouteImport } from './routes/register.success'
import { Route as AppCasesDemoCaseRouteImport } from './routes/app.cases.demo-case'
import { Route as AppCasesNewProcessRouteImport } from './routes/app.cases.new.process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordRoute = AppRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppVeritasRoute = AppVeritasRouteImport.update({
  id: '/veritas',
  path: '/veritas',
  getParentRoute: () => AppRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterProfessionalRoute = RegisterProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterProfileRoute = RegisterProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => RegisterRoute,
} as any)
const AppCasesDemoCaseRoute = AppCasesDemoCaseRouteImport.update({
  id: '/demo-case',
  path: '/demo-case',
  getParentRoute: () => AppCasesRoute,
} as any)
const AppCasesNewProcessRoute = AppCasesNewProcessRouteImport.update({
  id: '/new/process',
  path: '/new/process',
  getParentRoute: () => AppCasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRouteWithChildren
  '/app/cases': typeof AppCasesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/record': typeof AppRecordRoute
  '/app/search': typeof AppSearchRoute
  '/app/veritas': typeof AppVeritasRoute
  '/register/professional': typeof RegisterProfessionalRoute
  '/register/profile': typeof RegisterProfileRoute
  '/register/success': typeof RegisterSuccessRoute
  '/app/': typeof AppIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/app/cases/demo-case': typeof AppCasesDemoCaseRoute
  '/app/cases/new/process': typeof AppCasesNewProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/app/cases': typeof AppCasesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/record': typeof AppRecordRoute
  '/app/search': typeof AppSearchRoute
  '/app/veritas': typeof AppVeritasRoute
  '/register/professional': typeof RegisterProfessionalRoute
  '/register/profile': typeof RegisterProfileRoute
  '/register/success': typeof RegisterSuccessRoute
  '/app': typeof AppIndexRoute
  '/register': typeof RegisterIndexRoute
  '/app/cases/demo-case': typeof AppCasesDemoCaseRoute
  '/app/cases/new/process': typeof AppCasesNewProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRouteWithChildren
  '/app/cases': typeof AppCasesRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/record': typeof AppRecordRoute
  '/app/search': typeof AppSearchRoute
  '/app/veritas': typeof AppVeritasRoute
  '/register/professional': typeof RegisterProfessionalRoute
  '/register/profile': typeof RegisterProfileRoute
  '/register/success': typeof RegisterSuccessRoute
  '/app/': typeof AppIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/app/cases/demo-case': typeof AppCasesDemoCaseRoute
  '/app/cases/new/process': typeof AppCasesNewProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/offline'
    | '/onboarding'
    | '/register'
    | '/app/cases'
    | '/app/notifications'
    | '/app/profile'
    | '/app/record'
    | '/app/search'
    | '/app/veritas'
    | '/register/professional'
    | '/register/profile'
    | '/register/success'
    | '/app/'
    | '/register/'
    | '/app/cases/demo-case'
    | '/app/cases/new/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/offline'
    | '/onboarding'
    | '/app/cases'
    | '/app/notifications'
    | '/app/profile'
    | '/app/record'
    | '/app/search'
    | '/app/veritas'
    | '/register/professional'
    | '/register/profile'
    | '/register/success'
    | '/app'
    | '/register'
    | '/app/cases/demo-case'
    | '/app/cases/new/process'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/offline'
    | '/onboarding'
    | '/register'
    | '/app/cases'
    | '/app/notifications'
    | '/app/profile'
    | '/app/record'
    | '/app/search'
    | '/app/veritas'
    | '/register/professional'
    | '/register/profile'
    | '/register/success'
    | '/app/'
    | '/register/'
    | '/app/cases/demo-case'
    | '/app/cases/new/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OfflineRoute: typeof OfflineRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases': {
      id: '/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/record': {
      id: '/app/record'
      path: '/record'
      fullPath: '/app/record'
      preLoaderRoute: typeof AppRecordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veritas': {
      id: '/app/veritas'
      path: '/veritas'
      fullPath: '/app/veritas'
      preLoaderRoute: typeof AppVeritasRouteImport
      parentRoute: typeof AppRoute
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/professional': {
      id: '/register/professional'
      path: '/professional'
      fullPath: '/register/professional'
      preLoaderRoute: typeof RegisterProfessionalRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/profile': {
      id: '/register/profile'
      path: '/profile'
      fullPath: '/register/profile'
      preLoaderRoute: typeof RegisterProfileRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/success': {
      id: '/register/success'
      path: '/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/app/cases/demo-case': {
      id: '/app/cases/demo-case'
      path: '/demo-case'
      fullPath: '/app/cases/demo-case'
      preLoaderRoute: typeof AppCasesDemoCaseRouteImport
      parentRoute: typeof AppCasesRoute
    }
    '/app/cases/new/process': {
      id: '/app/cases/new/process'
      path: '/new/process'
      fullPath: '/app/cases/new/process'
      preLoaderRoute: typeof AppCasesNewProcessRouteImport
      parentRoute: typeof AppCasesRoute
    }
  }
}

interface AppCasesRouteChildren {
  AppCasesDemoCaseRoute: typeof AppCasesDemoCaseRoute
  AppCasesNewProcessRoute: typeof AppCasesNewProcessRoute
}

const AppCasesRouteChildren: AppCasesRouteChildren = {
  AppCasesDemoCaseRoute: AppCasesDemoCaseRoute,
  AppCasesNewProcessRoute: AppCasesNewProcessRoute,
}

const AppCasesRouteWithChildren = AppCasesRoute._addFileChildren(
  AppCasesRouteChildren,
)

interface AppRouteChildren {
  AppCasesRoute: typeof AppCasesRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecordRoute: typeof AppRecordRoute
  AppSearchRoute: typeof AppSearchRoute
  AppVeritasRoute: typeof AppVeritasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasesRoute: AppCasesRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecordRoute: AppRecordRoute,
  AppSearchRoute: AppSearchRoute,
  AppVeritasRoute: AppVeritasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface RegisterRouteChildren {
  RegisterProfessionalRoute: typeof RegisterProfessionalRoute
  RegisterProfileRoute: typeof RegisterProfileRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterProfessionalRoute: RegisterProfessionalRoute,
  RegisterProfileRoute: RegisterProfileRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OfflineRoute: OfflineRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
